version: '3.1'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: <SEU_RDS_ENDPOINT>
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: <SEU_DB_PASSWORD>
      WORDPRESS_DB_NAME: <NOME_DO_SEU_DB>
    volumes:
      - wp_data:/var/www/html

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=<EFS_DNS_NAME>,rw,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
      device: ":/"